version: '3.4'

services:
  moviesApp:
    image: movies-app
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 5000:5000
